title: "El tío Emil"
show_excerpts: true
description: >-
  These are not the droids you were looking for.
baseurl: ""
url: "https://www.eltioemil.es"
github_username:  eltioemil
linkedin_username: eltioemil

# Build settings
# This theme overrides minima theme
theme: minima

plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
