# Site settings
title:          Emil
description:    "Emil's site"
baseurl:        ""
url:            ""

# Google Analytics
google_analytics: UA—48320717-3

# Author
author:
  name:         El tío Emil
  url:          https://eltioemil.es
  email:        nope@nope.es

# Build settings
markdown: kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - jekyll-admin
  - jekyll-sitemap

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10

# Excludes
exclude: [ Gemfile, Gemfile.lock, emil.gemspec ]